Web.App/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.App.Core.Models;
using Web.App.Core.Services.Interfaces;

namespace Web.App.Controllers
{
    public class AccountsController : Controller
    {

        /// <summary>
        /// Account service.
        /// </summary>
        private readonly IAccountService _accountService;

        /// <summary>
        /// Client service.
        /// </summary>
        private readonly IClientService _clientService;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="accountService"></param>
        /// <param name="clientService"></param>
        public AccountsController(IAccountService accountService, IClientService clientService)
        {
            _accountService = accountService;
            _clientService = clientService;
        }

        /// <summary>
        /// Get accounts.        
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Account> accounts = await _accountService.GetAllAsync();

                return View(accounts);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        /// <summary>
        /// View add new accounts.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ViewBag.Clients =  new SelectList(await _clientService.GetAllAsync(), "Id", "FullName");
            return View();
        }

        /// <summary>
        /// Add new account.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Add(Account model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = await _accountService.AddAsync(model);
                    if (id > 0) return RedirectToAction(nameof(Index)); 
                    else return View(model);                    
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }


        /// <summary>
        /// Get client by id.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            try
            {
                Account model = await _accountService.GetByIdAsync(Id);
                if (model == null)
                {
                    return NotFound();
                }
                ViewBag.Clients = new SelectList(await _clientService.GetAllAsync(), "Id", "FullName");
                return View(model);
            }
            catch (Exception ex)
            {

                return BadRequest(ex.Message);
            }
        }


        /// <summary>
        /// Update Account.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Update(Account model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = await _accountService.UpdateAsync(model);
                    if (id > 0) return RedirectToAction(nameof(Index));
                    else return View(model);
                }
                return View(model);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> Transactions(int Id)
        {
            try
            {
                Account model = await _accountService.GetByIdAsync(Id);
                if (model == null)
                {
                    return NotFound();
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

    }
}

Web.App/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Web.App.Core.Models;
using Web.App.Core.Services.Interfaces;

namespace CreditPlatform.Controllers
{
    public class ClientsController : Controller
    {
        /// <summary>
        /// Logger service.
        /// </summary>
        private readonly ILogger<ClientsController> _logger;
        /// <summary>
        /// Client service.
        /// </summary>
        private readonly IClientService _clientService;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="clientService"></param>
        public ClientsController(ILogger<ClientsController> logger, IClientService clientService)
        {
            _logger = logger;
            _clientService = clientService;
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Client> clients = await _clientService.GetAllAsync();
                return View(clients);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        /// <summary>
        /// View add new user.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Add new user.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Add(Client model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = await _clientService.AddAsync(model);
                    if (id > 0)
                        return RedirectToAction(nameof(Index));
                    else
                        return View(model);
                }

                return View(model);


            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        /// <summary>
        /// Get client by id.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            try
            {
                Client model = await _clientService.GetByIdAsync(Id);
                if (model == null)
                {
                    return NotFound();
                }

                return View(model);
            }
            catch (Exception ex)
            {

                return BadRequest(ex.Message);
            }
        }
        
        
        /// <summary>
        /// Get client by id.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Update(Client model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = await _clientService.UpdateAsync(model);
                    if (id > 0)
                        return RedirectToAction(nameof(Index));
                    else
                        return View(model);
                }
                return View(model);
            }
            catch (Exception ex)
            {

                return BadRequest(ex.Message);
            }
        }


        /// <summary>
        /// Delete client - GET.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            try
            {
                Client client = await _clientService.GetByIdAsync(Id);
                if (client == null)
                {
                    return NotFound();
                }

                return View(client);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Delete client - POST
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int Id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = await _clientService.DeleteAsync(Id);
                    if (id > 0)
                        return RedirectToAction(nameof(Index));
                    else
                        return BadRequest();
                }
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(Activity.Current?.Id ?? HttpContext.TraceIdentifier);
        }
    }
}

Web.App/Controllers/MovementsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.App.Core.Models;
using Web.App.Core.Services.Interfaces;

namespace Web.App.Controllers
{
    public class MovementsController : Controller
    {
        /// <summary>
        /// Movements service.
        /// </summary>
        private readonly IMovementService _movementService;

        /// <summary>
        /// Account service.
        /// </summary>
        private readonly IAccountService _accountService;

        /// <summary>
        /// Types of movements service.
        /// </summary>
        private readonly ITypeMovementService _typeMovementService;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="movementRepository"></param>
        /// <param name="accountService"></param>
        public MovementsController(IMovementService movementRepository, IAccountService accountService, ITypeMovementService typeMovementService)
        {
            _movementService = movementRepository;
            _accountService = accountService;
            _typeMovementService = typeMovementService;
        }

        /// <summary>
        /// Get all movements.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Movement> movements = await _movementService.GetAllAsync();
            return View(movements);
        }

        /// <summary>
        /// Add new movements to account.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Add(int Id)
        {
            try
            {
                var account = await _accountService.GetByIdAsync(Id);

                if (account == null)
                {
                    return NotFound();
                }

                ViewBag.TypesMovements = new SelectList(await _typeMovementService.GetAllAsync(), "Id", "Name");
                return View(new Movement() { AccountId = account.Id, Account = account });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// Add new movement.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Add(Movement model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ViewBag.TypesMovements = new SelectList(await _typeMovementService.GetAllAsync(), "Id", "Name");
                    int id = 0;
                    var account = await _accountService.GetByIdAsync(model.Id);
                    if (model.TypeMovementId == 1)
                    {
                        if (model.Amount > account.CurrentBalance)
                        {
                            ModelState.AddModelError("Amount", $"The amount is greater than the balance ({account.CurrentBalance:C}).");
                            return View(model);
                        }
                    }
                    // Add movement.
                    id = await _movementService.AddAsync(model);
                    // Redirect to action.
                    if (id > 0) return RedirectToAction(nameof(AccountsController.Transactions), "Accounts",new { Id = model.Id });
                    else return View(model);

                }

                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

    }
}

Web.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Credit Platform</title>
    <meta name="author" content="name">
    <meta name="description" content="description here">
    <meta name="keywords" content="keywords,here">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" /> <!--Replace with your tailwind.css once created-->
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet"> <!--Totally optional :) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>

</head>

<body class="bg-gray-800 font-sans leading-normal tracking-normal mt-12">

    <header>
        <!--Nav-->
        <nav aria-label="menu nav" class="bg-gray-800 pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">

            <div class="flex flex-wrap items-center">
                <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
                    <a href="#" aria-label="Home">
                        @*<span class="text-xl pl-2"><i class="em em-grinning"></i></span>*@
                    </a>
                </div>

                <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
                    @*<span class="relative w-full">
                        <input aria-label="search" type="search" id="search" placeholder="Search" class="w-full bg-gray-900 text-white transition border border-transparent focus:outline-none focus:border-gray-400 rounded py-3 px-2 pl-10 appearance-none leading-normal">
                        <div class="absolute search-icon" style="top: 1rem; left: .8rem;">
                            <svg class="fill-current pointer-events-none text-white w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
                            </svg>
                        </div>
                    </span>*@
                </div>

                <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
                    <ul class="list-reset flex justify-between flex-1 md:flex-none items-center">                        
                        <li class="flex-1 md:flex-none md:mr-3">
                            <div class="relative inline-block">
                                <button onclick="toggleDD('myDropdown')" class="drop-button text-white py-2 px-2">
                                    <span class="pr-2"><i class="em em-robot_face"></i></span> Hi, User <svg class="h-3 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        @*<path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />*@
                                    </svg>
                                </button>
                                
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </header>


    <main>

        <div class="flex flex-col md:flex-row">
            <nav aria-label="alternative nav">
                <div class="bg-gray-800 shadow-xl h-20 fixed bottom-0 mt-12 md:relative md:h-screen z-10 w-full md:w-48 content-center">

                    <div class="md:mt-12 md:w-48 md:fixed md:left-0 md:top-0 content-center md:content-start text-left justify-between">
                        <ul class="list-reset flex flex-row md:flex-col pt-3 md:py-3 px-1 md:px-2 text-center md:text-left">
                            <li class="mr-3 flex-1">
                                <a asp-action="Index" asp-controller="Clients" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-pink-500">
                                    <i class="fas fa-tasks pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Clients</span>
                                </a>
                            </li>
                            <li class="mr-3 flex-1">
                                <a asp-action="Index" asp-controller="Accounts" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-purple-500">
                                    <i class="fa fa-envelope pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Accounts</span>
                                </a>
                            </li>
                            <li class="mr-3 flex-1">
                                <a asp-action="Index" asp-controller="Movements" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-purple-500">
                                    <i class="fas fa-chart-area pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Movements</span>
                                </a>
                            </li>
                            @*<li class="mr-3 flex-1">
                                <a href="#" class="block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500">
                                    <i class="fa fa-wallet pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 md:text-gray-200 block md:inline-block">Payments</span>
                                </a>
                            </li>*@
                        </ul>
                    </div>


                </div>
            </nav>
            <section class="w-full p-10">
                <div id="main" class="w-full main-content flex-1 bg-gray-100 mt-12 md:mt-2 pb-24 md:pb-5">
                    @RenderBody()
                </div>
            </section>
        </div>

    </main>




    <script>
        /*Toggle dropdown list*/
        function toggleDD(myDropMenu) {
            document.getElementById(myDropMenu).classList.toggle("invisible");
        }
        /*Filter dropdown options*/
        function filterDD(myDropMenu, myDropMenuSearch) {
            var input, filter, ul, li, a, i;
            input = document.getElementById(myDropMenuSearch);
            filter = input.value.toUpperCase();
            div = document.getElementById(myDropMenu);
            a = div.getElementsByTagName("a");
            for (i = 0; i < a.length; i++) {
                if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    a[i].style.display = "";
                } else {
                    a[i].style.display = "none";
                }
            }
        }
        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.drop-button') && !event.target.matches('.drop-search')) {
                var dropdowns = document.getElementsByClassName("dropdownlist");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (!openDropdown.classList.contains('invisible')) {
                        openDropdown.classList.add('invisible');
                    }
                }
            }
        }
    </script>


</body>

</html>